name: 06 - Activity Types
on: 
    pull_request_target: 
        types: 
            - opened
            - synchronize
        branches: 
            - develop


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: ShowMessage
              run: echo 'Running whenever a PR is opened or synchronized AND base branch is develop'
    